auth-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV=test
  image: partixyz/auth-api:0.3.1-2-g6b80b7b
  links:
    - db:auth-db
  ports:
    - 3031:3030
db:
  image: postgres:9.4
  ports:
    - 5432:5432
users-api:
  environment:
    - DB_USER=postgres
    - RAILS_ENV=test
  image: partixyz/users-api:0.2.0-5-g7fd4373
  links:
    - db:users-db
    - auth-api
  ports:
    - 3030:3030
users-ui:
  environment:
    - APIHOST=users-api
    - APIPORT=3030
    - RAILS_ENV=test
  image: partixyz/users-ui:current
  links:
    - users-api
  ports:
    - 8080:8080
